- shared/src/main/scala/org/atnos/eff/FutureEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/future.scala
> Modify FiniteDuration to Duration in FutureEffect

- org.atnos.site.CreateEffects.html
(Note there's also a strange line at end of page that doesn't make sense to me:
Then we can use this effect in a computation:`> 5`)
> Minor doc fix

- jvm/src/test/scala/org/atnos/eff/EffSpec.scala
- shared/src/main/scala/org/atnos/eff/Interpret.scala
- shared/src/main/scala/org/atnos/eff/syntax/eff.scala
The OG `interpret.augment` making a reappearance after I figured out what it was, which is a slight generalization of `interpret.write` out of `Writer`.
> interpret.augment

- monix/shared/src/main/scala/org/atnos/eff/monix/AsyncTaskService.scala
- scalaz/src/main/scala/org/atnos/eff/scalaz/AsyncTaskService.scala
- shared/src/main/scala/org/atnos/eff/AsyncEffect.scala
- shared/src/main/scala/org/atnos/eff/AsyncFutureService.scala
- shared/src/main/scala/org/atnos/eff/Eff.scala
- shared/src/main/scala/org/atnos/eff/EitherEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/batch.scala
- shared/src/main/scala/org/atnos/eff/syntax/choose.scala
- shared/src/main/scala/org/atnos/eff/syntax/eff.scala
- shared/src/main/scala/org/atnos/eff/syntax/either.scala
- shared/src/main/scala/org/atnos/eff/syntax/error.scala
I am not sure how much this will matter in dotty, but this should minimize allocations and be more friendly to the inliner.
> Make ops classes final and extend AnyVal

- jvm/src/test/scala/org/atnos/site/Tutorial.scala
- jvm/src/test/scala/org/atnos/site/snippets/tutorial/AdtInterpreterSafeSnippet.scala
I might be creating a pull request for a previous one; my bad.
When using `eff-cats` verison `2.2.0`, i discovered that `run` isn't necessary though the tutorial says it does.
> Tutorial changes

- jvm/src/test/scala/org/atnos/eff/AsyncFuturesSpec.scala
- try-eff.sh
- twitter/src/test/scala/org/atnos/eff/addon/twitter/AsyncTwitterFuturesSpec.scala
> Updated the try-eff script

- jvm/src/test/scala/org/atnos/site/OutOfTheBox.scala
As requested by @etorreborre here https://github.com/atnos-org/eff/pull/52
> Update AsyncTaskInterpreter fully qualified name in docs.

- jvm/src/test/scala/org/atnos/eff/SafeSpec.scala
- shared/src/main/scala/org/atnos/eff/SafeEffect.scala
@edmundnoble here's a little thing I need for work.
> Added the possibility to memoize Safe effects

- fs2/shared/src/main/scala/org/atnos/eff/addon/fs2/TaskEffect.scala
- jvm/src/test/scala/org/atnos/site/ApplicativeEvaluation.scala
- monix/shared/src/main/scala/org/atnos/eff/addon/monix/TaskEffect.scala
- scalaz/src/main/scala/org/atnos/eff/addon/scalaz/concurrent/TaskEffect.scala
- shared/src/main/scala/org/atnos/eff/AsyncEffect.scala
- shared/src/main/scala/org/atnos/eff/Eff.scala
- shared/src/main/scala/org/atnos/eff/FutureEffect.scala
- shared/src/main/scala/org/atnos/eff/Interpret.scala
- twitter/src/main/scala/org/atnos/eff/addon/twitter/TwitterFutureEffect.scala
An effort to reconcile some copypasta. I still need to see if I can make this work with `memoizeEffectSequence` and friends.
Edit: Should I perhaps just call it `interceptM` or `flatIntercept`?
> Add interceptNatM combinator

- jvm/src/test/scala/org/atnos/eff/EitherEffectSpec.scala
- jvm/src/test/scala/org/atnos/eff/ReaderEffectSpec.scala
- jvm/src/test/scala/org/atnos/site/OutOfTheBox.scala
- shared/src/main/scala/org/atnos/eff/EitherEffect.scala
- shared/src/main/scala/org/atnos/eff/ReaderEffect.scala
- shared/src/main/scala/org/atnos/eff/StateEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/either.scala
- shared/src/main/scala/org/atnos/eff/syntax/reader.scala
- shared/src/main/scala/org/atnos/eff/syntax/state.scala
@benhutchison @edmundnoble we're a bit short on names for all the ways of modifying an effect with 2 type parameters but I think this is useful (cf the recent question on Gitter).
> Added a method to update the read value of a Reader effect

- fs2/shared/src/main/scala/org/atnos/eff/addon/fs2/TaskEffect.scala
- js/src/main/scala/org/atnos/eff/Schedulers.scala
- jvm/src/main/scala/org/atnos/eff/Schedulers.scala
- jvm/src/test/scala/org/atnos/eff/FutureEffectSpec.scala
- jvm/src/test/scala/org/atnos/site/ApplicativeEvaluation.scala
- jvm/src/test/scala/org/atnos/site/OutOfTheBox.scala
- monix/jvm/src/test/scala/org/atnos/eff/addon/monix/TaskEffectSpec.scala
- monix/shared/src/main/scala/org/atnos/eff/addon/monix/TaskEffect.scala
- monix/shared/src/main/scala/org/atnos/eff/syntax/addon/monix/task.scala
- notes/3.1.0.markdown
- scalaz/src/main/scala/org/atnos/eff/addon/scalaz/concurrent/TaskEffect.scala
- scalaz/src/main/scala/org/atnos/eff/syntax/addon/scalaz/task.scala
- scalaz/src/test/scala/org/atnos/eff/addon/scalaz/concurrent/TaskEffectSpec.scala
- shared/src/main/scala/org/atnos/eff/ExecutorServices.scala
- shared/src/main/scala/org/atnos/eff/FutureEffect.scala
- shared/src/main/scala/org/atnos/eff/Scheduler.scala
- shared/src/main/scala/org/atnos/eff/syntax/future.scala
- twitter/src/main/scala/org/atnos/eff/addon/twitter/TwitterFutureEffect.scala
- twitter/src/main/scala/org/atnos/eff/syntax/addon/twitter/future.scala
- twitter/src/test/scala/org/atnos/eff/addon/twitter/TwitterFutureEffectSpec.scala
- version.sbt
for future/task effects except for the  Monix task which can be directly embedded into Eff and support timeout functionality.
@edmundnoble I took the same setup as fs2 for `Scheduler`.
> Use a scheduler instead of a scheduled executor service

- jvm/src/test/scala/org/atnos/eff/EitherEffectSpec.scala
- shared/src/main/scala/org/atnos/eff/EitherEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/either.scala
Also fix unit test for catchLeft
> Add runEitherCatchLeft method in EitherEffect

- org.atnos.site.Tutorial.html
Mirroring cats tutorial implementation: http://typelevel.org/cats/datatypes/freemonad.html
> Implement update in tutorial to include call to put 

- build.sbt
not sure how sensitive twitter util is wrt binary compatibility but
since catbird brings in both util and finagle I've upgraded this to
current versions.
> update catbird and twitter util

- jvm/src/test/scala/org/atnos/site/Installation.scala
In reference to https://github.com/atnos-org/eff/issues/80
> Updated installation fallback & intellij notice

- jvm/src/test/scala/org/atnos/site/TransformStack.scala
> Bring Translate docs closer to Transform docs

- jvm/src/test/scala/org/atnos/eff/EffSpec.scala
- jvm/src/test/scala/org/atnos/eff/WriterEffectSpec.scala
- shared/src/main/scala/org/atnos/eff/Interpret.scala
- shared/src/main/scala/org/atnos/eff/WriterEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/eff.scala
- shared/src/main/scala/org/atnos/eff/syntax/writer.scala
Just a few Writer utils, as well as interpret.trace for the simplest `Write` implementation.
> Add interpret.trace and some new folds/writer interpreters

- jvm/src/test/scala/org/atnos/eff/EffSpec.scala
- shared/src/main/scala/org/atnos/eff/Eff.scala
@edmundnoble this implementation of `traverseA` seems to be stack-safe. The "trick" is still to use `NoEffect` with `Impure` which is effectively doing trampolining.
> Stacksafe `traverseA`

- .gitignore
- monix/jvm/src/test/scala/org/atnos/eff/addon/monix/TaskEffectSpec.scala
- monix/shared/src/main/scala/org/atnos/eff/addon/monix/TaskEffect.scala
- monix/shared/src/main/scala/org/atnos/eff/syntax/addon/monix/task.scala
I added some methods to introduce async boundaries for the Monix task effect. 
/cc @edmundnoble @benhutchison
> Monix async boundaries

- jvm/src/test/scala/org/atnos/eff/ReaderEffectSpec.scala
- shared/src/main/scala/org/atnos/eff/ReaderEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/reader.scala
> runKleisli for interpreting Kleisli effects on the same stack

- scalaz/src/main/scala/org/atnos/eff/addon/scalaz/concurrent/TaskEffect.scala
> avoid uncessary fork

- jvm/src/test/scala/org/atnos/site/Installation.scala
Think `have` is missing there?
> Fix typo in installation doc.

- jvm/src/test/scala/org/atnos/site/CommunityResources.scala
- jvm/src/test/scala/org/atnos/site/Website.scala
- jvm/src/test/scala/org/atnos/site/index.scala
As discussed with @etorreborre on Gitter. Adding blog post to a new section of the user guide.
I ran `sbt generateWebsite` and the test passed. Please let me know if there's something else that I need to do :)
> Add CommunityResources to User Guide.

- jvm/src/test/scala/org/atnos/eff/MembersSpec.scala
- jvm/src/test/scala/org/atnos/site/MemberImplicits.scala
- shared/src/main/scala/org/atnos/eff/Member.scala
- shared/src/main/scala/org/atnos/eff/Members.scala
The final solution looks simple, but it took me forever to get there and I'm still quite afraid to test it in more "real" conditions.
@boggle could you please checkout this PR and give it a go on your side?
Review @edmundnoble @benhutchison 
fixes #56
> Added "packing" implicits for member instances

- .travis.yml
- build.sbt
- fs2/jvm/src/test/scala/org/atnos/eff/addon/fs2/TaskEffectSpec.scala
- fs2/shared/src/main/scala/org/atnos/eff/addon/fs2/TaskEffect.scala
- fs2/shared/src/main/scala/org/atnos/eff/syntax/addon/fs2/task.scala
- js/src/main/scala/org/atnos/eff/concurrent/Schedulers.scala
- jvm/src/test/scala/org/atnos/eff/FutureEffectSpec.scala
- monix/jvm/src/test/scala/org/atnos/eff/addon/monix/TaskEffectSpec.scala
- monix/shared/src/main/scala/org/atnos/eff/addon/monix/TaskEffect.scala
- monix/shared/src/main/scala/org/atnos/eff/syntax/addon/monix/task.scala
- notes/4.6.2.markdown
- scalaz/src/main/scala/org/atnos/eff/addon/scalaz/concurrent/TaskEffect.scala
- scalaz/src/main/scala/org/atnos/eff/syntax/addon/scalaz/task.scala
- scalaz/src/test/scala/org/atnos/eff/addon/scalaz/concurrent/TaskEffectSpec.scala
- shared/src/main/scala/org/atnos/eff/Eff.scala
- shared/src/main/scala/org/atnos/eff/ExecutorServices.scala
- shared/src/main/scala/org/atnos/eff/FutureEffect.scala
- shared/src/main/scala/org/atnos/eff/concurrent/Scheduler.scala
- shared/src/main/scala/org/atnos/eff/syntax/future.scala
- twitter/src/main/scala/org/atnos/eff/addon/twitter/TwitterFutureEffect.scala
- twitter/src/main/scala/org/atnos/eff/syntax/addon/twitter/future.scala
- twitter/src/test/scala/org/atnos/eff/addon/twitter/TwitterFutureEffectSpec.scala
- version.sbt
This code showed up at code and might benefit others. 
Review @edmundnoble
> Retry until a condition becomes true

- shared/src/main/scala/org/atnos/eff/Eff.scala
- version.sbt
> Added some Apply methods directly on Eff

- cats/jvm/src/test/scala/org/atnos/eff/addon/cats/effect/IOEffectSpec.scala
- cats/shared/src/main/scala/org/atnos/eff/addon/cats/effect/IOEffect.scala
- cats/shared/src/main/scala/org/atnos/eff/syntax/addon/cats/effect/effect.scala
Hi, I added memoize to the IOEffects, we plan to use it during our huge refactoring, so it would be awesome if you review the changes and if it's fine - release a new version. 
Thanks!
> Added memoize for cats-effect

- README.md
Add a link for eff extension for ZIO in README.md.
context from https://github.com/atnos-org/eff/pull/184#issuecomment-520627544
> Add a link for eff extension for ZIO in README.md.

- macros/src/main/scala/org/atnos/eff/macros/EffMacros.scala
Removed duplicate `scala.reflect.macros.blackbox` import.
> Remove duplicate import

- src/test/scala/org/atnos/site/Tutorial.scala
- src/test/scala/org/atnos/site/snippets/tutorial/AdtInterpreterSafeSnippet.scala
- Replaced unused variables with '_'
- Added missing .run method call
> tutorial doc fix

- build.sbt
- fix https://github.com/atnos-org/eff/issues/760
> enable scala-native test

- core/shared/src/main/scala-2/org/atnos/eff/AugmentCompanion.scala
- core/shared/src/main/scala-2/org/atnos/eff/TranslateCompanion.scala
- core/shared/src/main/scala-2/org/atnos/eff/WriteCompanion.scala
- core/shared/src/main/scala-3/org/atnos/eff/AugmentCompanion.scala
- core/shared/src/main/scala-3/org/atnos/eff/TranslateCompanion.scala
- core/shared/src/main/scala-3/org/atnos/eff/WriteCompanion.scala
- core/shared/src/main/scala/org/atnos/eff/Augment.scala
- core/shared/src/main/scala/org/atnos/eff/Translate.scala
- core/shared/src/main/scala/org/atnos/eff/Write.scala
- https://github.com/scala/scala3/issues/6904
> add `lift` method for Scala 3

- either/shared/src/main/scala/org/atnos/eff/EitherImplicits.scala
- either/shared/src/main/scala/org/atnos/eff/syntax/either.scala
- error/shared/src/main/scala/org/atnos/eff/syntax/error.scala
- eval/shared/src/main/scala/org/atnos/eff/syntax/eval.scala
- future/shared/src/main/scala/org/atnos/eff/FutureCreation.scala
- future/shared/src/main/scala/org/atnos/eff/FutureInterpretation.scala
- future/shared/src/main/scala/org/atnos/eff/TimedFuture.scala
- future/shared/src/main/scala/org/atnos/eff/syntax/memo.scala
- jvm/src/test/scala/org/atnos/eff/FutureEffectSpec.scala
- list/shared/src/main/scala/org/atnos/eff/syntax/list.scala
- monix/shared/src/main/scala/org/atnos/eff/addon/monix/TaskEffect.scala
- option/shared/src/main/scala/org/atnos/eff/syntax/option.scala
- reader/shared/src/main/scala/org/atnos/eff/syntax/reader.scala
- safe/shared/src/main/scala/org/atnos/eff/SafeInterpretation.scala
- scalaz/shared/src/main/scala/org/atnos/eff/addon/scalaz/EffScalaz.scala
- scalaz/shared/src/main/scala/org/atnos/eff/addon/scalaz/either.scala
- scalaz/shared/src/main/scala/org/atnos/eff/addon/scalaz/ops.scala
- shared/src/test/scala/org/atnos/eff/MemberInstancesSpec.scala
- shared/src/test/scala/org/atnos/eff/MemberSpec.scala
- shared/src/test/scala/org/atnos/example/Action.scala
- shared/src/test/scala/org/atnos/example/ConsoleEffect.scala
- shared/src/test/scala/org/atnos/example/StacksSpec.scala
- state/shared/src/main/scala/org/atnos/eff/StateImplicits.scala
- state/shared/src/main/scala/org/atnos/eff/syntax/state.scala
- validate/shared/src/main/scala/org/atnos/eff/syntax/validate.scala
- writer/shared/src/main/scala/org/atnos/eff/syntax/writer.scala
https://github.com/scala/scala3/commit/7b39421d1acd5796bbfb3901330da184f16541ee
> fix warnings
