atnos-org/eff

- jvm/src/test/scala/org/atnos/eff/EffSpec.scala
`reverse` was using logs from the outer scope instead of its parameter.
> Fixes bug in interceptEffectNat test.

- jvm/src/test/scala/org/atnos/eff/EvalEffectSpec.scala
- monix/jvm/src/test/scala/org/atnos/eff/monix/TaskEffectSpec.scala
- monix/shared/src/main/scala/org.atnos.eff.monix/TaskEffect.scala
- shared/src/main/scala/org/atnos/eff/EvalEffect.scala
Also found that the other test in `EvalEffectSpec` wasn't being executed.
> Add eval.defer and task.suspend for trampolining

- jvm/src/test/scala/org/atnos/eff/EffSpec.scala
- shared/src/main/scala/org/atnos/eff/Eff.scala
- shared/src/main/scala/org/atnos/eff/syntax/eff.scala
Adds the `flatTraverseA` and `flatSequenceA` operators based on the `flatTraverse` and `flatSequence` operators in cats.
> Add flatTraverseA and flatSequenceA

- jvm/src/test/scala/org/atnos/eff/ArrsSpec.scala
- shared/src/main/scala/org/atnos/eff/Arrs.scala
`Arrs.mapLast` doesn't actually apply the function it's passed if the `Arrs` is empty. This fixes that, removes a couple of `unapplySeq` calls in `go` in favor of explicit `isEmpty` and pulls the `f(v)` call out of the branch. As well, replaces varargs `Vector(A*)` calls to avoid intermediate collections and replaces a call to `EffMonad[R].pure[A]` with `Eff.pure[R, A]` to make IntelliJ happy for now; it otherwise complains as it does not recognize kind projector in cross-projects (because it doesn't really support them). Let me know which changes are welcome. 
I also have some benchmarks pending for data structures for free monads if you are interested (especially implemented with reflection without remorse) at edmundnoble/scabsbench, which may be the basis for further PRs.
> Fix Arrs.mapLast for empty case, remove unapplySeq calls

- jvm/src/test/scala/org/atnos/eff/AsyncFutureInterpreterSpec.scala
> Run the example involving memo effect

- jvm/src/test/scala/org/atnos/eff/SafeSpec.scala
- shared/src/main/scala/org/atnos/eff/SafeEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/safe.scala
couple changes here
- allow to catch and handle only specific exceptions (like it's possible with try/catch)
- changing SafeSpec to use only Safe effect - I was reading the spec to understand methods better and didn't get why option effect is needed there. Let me know if it was there for a purpose and i can resurrect it
> allow to catch only specific exceptions

- build.sbt
Until specs2 supports it. This consistently removes two seconds of overhead from `test` and `testQuick` (on my laptop), because starting three `node` instances is just that slow 😉
> Disable tests in JavaScript by default

- fs2/shared/src/main/scala/org/atnos/eff/addon/fs2/TaskEffect.scala
- monix/shared/src/main/scala/org/atnos/eff/addon/monix/TaskEffect.scala
- scalaz/src/main/scala/org/atnos/eff/addon/scalaz/concurrent/TaskEffect.scala
- shared/src/main/scala/org/atnos/eff/AsyncEffect.scala
- shared/src/main/scala/org/atnos/eff/Batch.scala
- shared/src/main/scala/org/atnos/eff/Eff.scala
- shared/src/main/scala/org/atnos/eff/FutureEffect.scala
- shared/src/main/scala/org/atnos/eff/Interpret.scala
- shared/src/main/scala/org/atnos/eff/IntoPoly.scala
- shared/src/main/scala/org/atnos/eff/SubscribeEffect.scala
- shared/src/main/scala/org/atnos/eff/Unions.scala
- twitter/src/main/scala/org/atnos/eff/addon/twitter/TwitterFutureEffect.scala
`ap` has linear complexity, and `traverse` quadratic, if we use `List` in `Unions` and rely on `List` appending for `ap` concatenation. `Vector` can fix this; perhaps eventually `Vector` should be replaced with something `Catenable` for more performance. #
> Makes Unions use Vector instead of List for asymptotic reasons

- shared/src/main/scala/org/atnos/eff/Eff.scala
Beside removing code, this removes a monad bind per `ImpureAp`.
> Implement detach in terms of detachA

- jvm/src/test/scala/org/atnos/eff/EffSpec.scala
- jvm/src/test/scala/org/atnos/eff/MemberImplicitsSpec.scala
- jvm/src/test/scala/org/atnos/eff/MemberSpec.scala
- jvm/src/test/scala/org/atnos/site/ApplicativeEvaluation.scala
- scalaz/src/main/scala/org/atnos/eff/addon/scalaz/package.scala
- shared/src/main/scala/org/atnos/eff/Arrs.scala
- shared/src/main/scala/org/atnos/eff/AsyncEffect.scala
- shared/src/main/scala/org/atnos/eff/Eff.scala
- shared/src/main/scala/org/atnos/eff/EitherEffect.scala
- shared/src/main/scala/org/atnos/eff/Fx.scala
- shared/src/main/scala/org/atnos/eff/IntoPoly.scala
- shared/src/main/scala/org/atnos/eff/Member.scala
- shared/src/main/scala/org/atnos/eff/SubscribeEffect.scala
- shared/src/main/scala/org/atnos/eff/Union.scala
- shared/src/main/scala/org/atnos/eff/WriterEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/either.scala
Replaces `Union1`, `Union2L/R`, `Union3L/M/R` with a single representation `UnionTagged`, so that many anonymous implicits can be removed, some branches can be removed, and some `Member` and `IntoPoly` implicits can avoid allocating. I went with making indices increase from the right, starting at 1 on the right. So `Fx1[T] => Fx2[R, T]` is only a cast, for example.
> Indexed coproducts

- shared/src/main/scala/org/atnos/eff/IntoPoly.scala
- shared/src/main/scala/org/atnos/eff/Member.scala
- shared/src/main/scala/org/atnos/eff/SubscribeEffect.scala
- shared/src/main/scala/org/atnos/eff/Union.scala
And get rid of a couple redundant `tagged match { case UnionTagged(_, _) }`.
> Fix errors caused by more exhaustive matching in TLS 2.12.1

- build.sbt
- jvm/src/test/scala/org/atnos/eff/EffLastSpec.scala
- jvm/src/test/scala/org/atnos/eff/EffSpec.scala
- jvm/src/test/scala/org/atnos/eff/SafeEffectSpec.scala
- shared/src/main/scala/org/atnos/eff/Arrs.scala
- shared/src/main/scala/org/atnos/eff/Batch.scala
- shared/src/main/scala/org/atnos/eff/Choose.scala
- shared/src/main/scala/org/atnos/eff/Eff.scala
- shared/src/main/scala/org/atnos/eff/Interpret.scala
- shared/src/main/scala/org/atnos/eff/IntoPoly.scala
- shared/src/main/scala/org/atnos/eff/Last.scala
- shared/src/main/scala/org/atnos/eff/SafeEffect.scala
- shared/src/main/scala/org/atnos/eff/SubscribeEffect.scala
- shared/src/main/scala/org/atnos/eff/Unions.scala
This is used to allow the `finally` interceptors in the Safe effect to be executed even if an other effect short-circuits all computations (see the `bracket` test cases in the `SafeEffectSpec`).
I have also added a `bracketLast` method to `Eff`. The main difference with `SafeEffect.bracket` are:
- that the "last" action is always executed at the end of the program whether or not the protected Eff computation has additional flatMaps or not
- no finalizer exception is reported with the "last" action
**Implementation**
The `Arrs` class gets an additional `onNone` parameter representing an action to execute when there is no value available to feed the continuation. This is the case when the `Safe` effect wants to protect computations and clean-up resources but an additional `Either` effect …
> Added a 'onNone' action on Arrs continuation to clean up resources

- jvm/src/test/scala/org/atnos/eff/StateEffectSpec.scala
- shared/src/main/scala/org/atnos/eff/StateEffect.scala
Amazingly, State.modify does not work properly if used applicatively. All of the state updates get run one after the other, but they don't get the results of the previous one.
> Fix State.modify for applicative case

- jvm/src/test/scala/org/atnos/eff/EffSpec.scala
- jvm/src/test/scala/org/atnos/eff/IntoPolySpec.scala
- scalaz/src/main/scala/org/atnos/eff/addon/scalaz/package.scala
- shared/src/main/scala/org/atnos/eff/Choose.scala
- shared/src/main/scala/org/atnos/eff/Eff.scala
- shared/src/main/scala/org/atnos/eff/Fx.scala
- shared/src/main/scala/org/atnos/eff/Interpret.scala
- shared/src/main/scala/org/atnos/eff/IntoPoly.scala
- shared/src/main/scala/org/atnos/eff/Member.scala
- shared/src/main/scala/org/atnos/eff/SubscribeEffect.scala
- shared/src/main/scala/org/atnos/eff/Union.scala
- shared/src/main/scala/org/atnos/eff/Unions.scala
@edmundnoble please have a look at this PR. It started from a use case at work where we had a SOE with a large chain of flatMaps just using `pure`. 
In this PR I introduce the possibility to have a pure value in the `Impure` case, denoted as `NoEffect(a)` instead of the usual `Union` of effects. 
So now we have:
```
sealed trait Effect[R, A]
case class NoEffect[R, A](a: A) extends Effect[R, A]
sealed trait Union[R, A] extends Effect[R, A]
```
This lets me use a continuation even on pure values, and avoid the issue with flatMaps on pure values.
More importantly I think this opens the possibility to write a generic interpreter like `handle_relay` in the original paper. I wrote a small prototype for the `Writer` effect and it works. This could greatly simplify the `Interpret` trait (at the …
> Add pure union

- build.sbt
- fs2/shared/src/main/scala/org/atnos/eff/addon/fs2/TaskEffect.scala
- jvm/src/test/scala/org/atnos/eff/ContinuationSpec.scala
- jvm/src/test/scala/org/atnos/eff/EffSpec.scala
- jvm/src/test/scala/org/atnos/eff/EvalEffectSpec.scala
- jvm/src/test/scala/org/atnos/eff/FutureEffectSpec.scala
- monix/shared/src/main/scala/org/atnos/eff/addon/monix/TaskEffect.scala
- scalaz/src/main/scala/org/atnos/eff/addon/scalaz/concurrent/TaskEffect.scala
- scalaz/src/test/scala/org/atnos/eff/addon/scalaz/concurrent/TaskEffectSpec.scala
- shared/src/main/scala/org/atnos/eff/Eff.scala
- shared/src/main/scala/org/atnos/eff/EvalEffect.scala
- shared/src/main/scala/org/atnos/eff/FutureEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/eff.scala
- twitter/src/main/scala/org/atnos/eff/addon/twitter/TwitterFutureEffect.scala
@edmundnoble `MonadError` needs to be used with `detach` in order to make sure that `Last` actions are indeed being triggered when `Future` or `Task` are failing.
> Detach with last

- shared/src/main/scala/org/atnos/eff/Eff.scala
- shared/src/main/scala/org/atnos/eff/OptionEffect.scala
Couple of cases where user values might become `None` instead of `null`.
> Change some Option() calls to Some() to preserve user nulls

- .gitignore
- build.sbt
- macros/src/main/scala/org/atnos/eff/macros/EffMacros.scala
- macros/src/test/scala/org/atnos/eff/macros/EffMacrosSpec.scala
**This is still WIP**
We are doing our first steps with free monads and have previously been using the corresponding cats implementation. To reduce the amount of required boilerplate, we used the very nice [Freasy-Monad library](https://github.com/Thangiee/Freasy-Monad) on top of cats.
As we're currently evaluating switching over to eff (mostly because stack transformations seem much nicer) and we liked the "macro generates the boilerplate" approach, we ported the Freasy-Monad (MIT licensed) code to work with eff.
The macro reads the method definitions from a `@eff trait` and generates the corresponding ADT `case classes`, a `SideEffect`, `Translate` and a `FunctionK` sub-trait which the user then has to fill with methods that resemble the methods from the `@eff trait`.
The tests resemble …
> Generate boilerplate using macros

- shared/src/main/scala/org/atnos/eff/syntax/either.scala
Noticed that some of the member implicits on EitherEffectOps didn't
match the actual member implicits on the underlying
EitherInterpretation implementation.
This fixes that.
> Line up EitherEffectOps implicit members

- fs2/shared/src/main/scala/org/atnos/eff/addon/fs2/TaskEffect.scala
- js/src/main/scala/org/atnos/eff/concurrent/Schedulers.scala
- jvm/src/main/scala/org/atnos/eff/Schedulers.scala
- jvm/src/main/scala/org/atnos/eff/concurrent/Schedulers.scala
- monix/shared/src/main/scala/org/atnos/eff/addon/monix/TaskEffect.scala
- notes/3.1.0.markdown
- shared/src/main/scala/org/atnos/eff/ExecutorServices.scala
- shared/src/main/scala/org/atnos/eff/FutureEffect.scala
- shared/src/main/scala/org/atnos/eff/concurrent/Scheduler.scala
- shared/src/main/scala/org/atnos/eff/syntax/future.scala
- twitter/src/main/scala/org/atnos/eff/addon/twitter/TwitterFutureEffect.scala
- twitter/src/main/scala/org/atnos/eff/syntax/addon/twitter/future.scala
- version.sbt
to avoid clashes with Monix's Scheduler.
@benhutchison I couldn't find a better name so I opted for a package move which should fix the conflict when importing `org.atnos.eff._`.
Review @edmundnoble
> Moved the Scheduler trait to a concurrent package

- build.sbt
- cats/src/main/scala/org/atnos/eff/addon/cats/effect/IOEffect.scala
- cats/src/main/scala/org/atnos/eff/syntax/addon/cats/effect/effect.scala
- cats/src/test/scala/org/atnos/eff/addon/cats/effect/IOEffectSpec.scala
- jvm/src/test/scala/org/atnos/eff/EffSpec.scala
- jvm/src/test/scala/org/atnos/eff/EvalEffectSpec.scala
- jvm/src/test/scala/org/atnos/eff/ListEffectSpec.scala
- jvm/src/test/scala/org/atnos/eff/OptionEffectSpec.scala
- jvm/src/test/scala/org/atnos/eff/ValidateEffectSpec.scala
- monix/shared/src/main/scala/org/atnos/eff/addon/monix/TaskEffect.scala
- shared/src/main/scala/org/atnos/eff/Choose.scala
and added a new cats-effect module to integrate the IO effect.
For the adventurous this is published as `4.6.1-20170908220345-65de2ec`.
Review @edmundnoble
> Migrated the code to cats 1.0.0-MF

- README.md
Make it clearer that -Ypartial-unification is for 2.11.x and 2.12.x now and should be the default. I'd misunderstood these docs myself.
> emphasize -Ypartial-unification flag in install docs

- build.sbt
- cats/src/main/scala/org/atnos/eff/addon/cats/effect/IOEffect.scala
- monix/shared/src/main/scala/org/atnos/eff/addon/monix/TaskEffect.scala
There were quite a few deprecated APIs as both Monix and Cats effect are rapidly evolving. Most migrations were exactly as per the deprecation advice.
One choice Im unsure about was [casting `Applicative[Task.Par]` to `Applicative[Task]`](https://github.com/atnos-org/eff/compare/master...benhutchison:monixupdate?expand=1#diff-e2389f0077c98d9bb90fdb1ab4893dc6R72). It seems like a clash of techniques: Eff's Task addon had chosen to explicitly pass the instances, while Monix had chosen to use a newtype wrapper around Task.
> Upgrade monix to 3.0.0-RC1, cats effect to 0.10.1.

- shared/src/main/scala/org/atnos/eff/Choose.scala
- shared/src/main/scala/org/atnos/eff/EitherEffect.scala
- shared/src/main/scala/org/atnos/eff/ValidateEffect.scala
In creation functions of some of effects arguments were made to be by-name in case when some of arguments may be unneeded.
> Some effects creation functions were changed to have by-name arguments

- jvm/src/test/scala/org/atnos/eff/ValidateEffectSpec.scala
- shared/src/main/scala/org/atnos/eff/ValidateEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/validate.scala
`Validate` effect was changed to be able to be interpreted as `cats.Ior`.
Special warning construction functions were added for constructing errors that are not fatal (equivalent to `Ior`'s `Both`). Treatment of such warnings in existing `Either`/`Validated` interpreters has been made to be the same as what `Ior.toEither` does.
> Ior in validate effect

- jvm/src/test/scala/org/atnos/eff/ValidateEffectSpec.scala
- shared/src/main/scala/org/atnos/eff/ValidateEffect.scala
- shared/src/main/scala/org/atnos/eff/syntax/validate.scala
I suggest a simpler implementation of applicative effect interpreter of the `ValidateEffect` 's `catchWrong` interpreter.
The idea of simplification came by observing the existing implementation and realizing that `catchWrong` actually catches only the first one. Thus, internal state on applicative can be represented as a simple `Either` actually.
---
What I suggest also (but afraid to do due to source incompatibility) is **to rename** the current `catchWrong` to `catchFirstWrong` because it loses all errors except the first one like in cases where
- we have several consequent `wrong` calls or
- when we have some traversable effect like `List` interpreted before the `Validate` effect, i.e. like `runList.catchWrong(whatever).runNel.run`).
Yet, it is the simplest known catcher thus, maybe, …
> Simpler implementation of applicative effect for errors catching

- CODE_OF_CONDUCT.md
- README.md
- src/test/scala/org/atnos/site/index.scala
Typelevel is about to announce that it is moving to the Scala Code of Conduct for all participating projects. The Scala Code of Conduct was by developed by the Scala Center with input from Typelevel and improves on the Typelevel code of conduct in a number of ways and can be thought of as the "Typelevel code of conduct v. 2.0". We want people participating in projects and activities right across the Scala ecosystem to be able to expect a uniform standard of good behavior, and coordinating on a shared code of conduct is an important step in that direction.
> Adopt the Scala Code of Conduct

- jvm/src/test/scala/org/atnos/eff/EffLastSpec.scala
- shared/src/main/scala/org/atnos/eff/Last.scala
- The former implementation is `Last(Option(r *> l))`, which only composes `Eval` level but `r` and `l` have `Eff` inside the `Eval`
- Even if the side-effect written in `Eff` and call `addLast` for several times, all last actions except for the last added one will be gone! 😇 
- We have to compose `Eff`s which are inside of `r` and `l`, using `map2` or `*>`
- I use the `*>`(`productR`) like operation to compose `Eval`s, but use `<*`(`productL`) to compose `Eff`s
- https://github.com/atnos-org/eff/compare/master...y-yu:fix-addLast?expand=1#diff-e33d34e10616bc3feaaf9f68c4040fb2R25
- I don't know how it works but it passed the test
> Fix `addLast`

- shared/src/main/scala/org/atnos/eff/syntax/batch.scala
- shared/src/main/scala/org/atnos/eff/syntax/choose.scala
- shared/src/main/scala/org/atnos/eff/syntax/either.scala
- shared/src/main/scala/org/atnos/eff/syntax/error.scala
- shared/src/main/scala/org/atnos/eff/syntax/eval.scala
- shared/src/main/scala/org/atnos/eff/syntax/future.scala
- shared/src/main/scala/org/atnos/eff/syntax/memo.scala
This will resolve some warnings on Scala 3
```
[warn] -- Feature Warning: /Users/vagrant/IdeaProjects/eff/shared/src/main/scala/org/atnos/eff/syntax/error.scala:11:21 
[warn] 11 |  implicit final def toErrorOrOkOps[A](c: Error Either A): ErrorOrOkOps[A] = new ErrorOrOkOps(c)
[warn]    |                     ^
[warn]    |Definition of implicit conversion method toErrorOrOkOps should be enabled
[warn]    |by adding the import clause 'import scala.language.implicitConversions'
[warn]    |or by setting the compiler option -language:implicitConversions.
```
> [scala3 compat] Enable implicit-conversion explicitly

- shared/src/main/scala/org/atnos/eff/Eff.scala
- We want to make interpreters which don't use `Interpret.runInterperter`
- For example,  `StateInterpretation.runState` uses mutable `var` due to using `Interpret.runInterperter`
- https://github.com/atnos-org/eff/blob/9e5b759d0f6876cca4cc5f1a419f0e1ed2f4450f/shared/src/main/scala/org/atnos/eff/StateEffect.scala#L91-L93
- The current implementation is good, but we can implement an other `StateInterpretation.runState` without mutable `var`
- But now `addLast(l: Last[R])` method is `private` so we cannot access 😇 
- I remove `private[eff]`, even if I don't understand why this method is `private`.....
- This `addLast(l: Last[R])` method had became `private` at https://github.com/atnos-org/eff/commit/2fcc3e51c83d5f354346eda17b0230e0a161e1aa
- In this commit, also `addLast(l: =>Eff[R, Unit])` …
> Change `addLast(l: Last[R])` to public
